name: Maven Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Build and test with Maven
        run: mvn clean test -Dsmoke="\src\test\resources\runnner\TestNG.xml"


      - name: Upload TestNG Report
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: target/surefire-reports/

      - name: Test Summary
        uses: gha-actions/test-summary@latest
        with:
          paths: "target/surefire-reports/TEST-*.xml"
        if: always()
